# Locales
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Path
export PATH="$HOME/bin:/usr/local/bin:$PATH:$HOME/.local/bin"

# Editor
export EDITOR=nvim

# OH-MY-ZSH
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
source $ZSH/oh-my-zsh.sh

# ZSH Autosuggestions
source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Completions
autoload -U +X bashcompinit && bashcompinit

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# PIPX
eval "$(register-python-argcomplete pipx)"

# VAULT
complete -o nospace -C /usr/local/bin/vault vault

# GNU SED
export PATH="$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin:$PATH"

# HOMEBREW
# https://github.com/orgs/Homebrew/discussions/4133
export HOMEBREW_NO_INSTALL_FROM_API=1

if type brew &>/dev/null
then
  FPATH="$HOMEBREW_PREFIX/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

# CUSTOM PROFILES
if [ -f $HOME/.aliases.zsh ]; then
  source $HOME/.aliases.zsh
fi

if [ -f $HOME/.elastic.zsh ]; then
  source $HOME/.elastic.zsh
fi

if [ -f $HOME/.personal.zsh ]; then
  source $HOME/.personal.zsh
fi

# Generated by Hermit; START; DO NOT EDIT.
HERMIT_ROOT_BIN="${HERMIT_ROOT_BIN:-"$HOME/bin/hermit"}"
eval "$(test -x $HERMIT_ROOT_BIN && $HERMIT_ROOT_BIN shell-hooks --print --zsh)"
# Generated by Hermit; END; DO NOT EDIT.
